### ISSUE TITLE
Allow to point sysbench to mysql router or proxysql

### ISSUE THREAD

**Issue by markusalbe** [ihanick/anydbver#24]
Hey Nickolay! Here's one idea that came up today while doing some tests:

Currently sysbench can point to a mysql or pg node, but it would be very useful if you coudl allow to point the sysbench to a mysql-router or proxysql node, or a pgBouncer node.  

An alternative would be to allow sysbench to specify a port for the target mysql/pg node.
Another alternative would be to use port 3306 for the proxies/routers (this seems less tempting)

**Comment by ihanick** [comment]
Hi @markusalbe ,
I've added a port  sub command and implemented it for mysql (currently not for postgresql):
added to the https://github.com/ihanick/anydbver/releases/tag/v0.1.6 (works both with go binary and python script)

```
anydbver deploy node0 ps:8.0,group-replication node1 ps:8.0,group-replication,master=node0 node2 ps:8.0,mysql-router,master=node0 node3 ps:8.0 sysbench:latest,mysql=node2,port=6446,oltprw
time anydbver exec node3 -- /usr/local/bin/run_sysbench.sh
```
