### ISSUE TITLE
Generate screen/tmux session for the deployment

### ISSUE THREAD

**Issue by markusalbe** [ihanick/anydbver#25]
Hey Nickolay! Here's another idea:

At the end of deployment generate `screen`/`tmux` config lines to have a session to each deployed node, for example in my `~/.screenrc` I added:

```
screen -t Client 0 /home/marcos.albe/anydbver/anydbver --namespace=gr ssh node0
screen -t DC1_N1 1 /home/marcos.albe/anydbver/anydbver --namespace=gr ssh node1
screen -t DC1_N2 2 /home/marcos.albe/anydbver/anydbver --namespace=gr ssh node2
screen -t DC1_N3 3 /home/marcos.albe/anydbver/anydbver --namespace=gr ssh node3
screen -t DC2_N1 4 /home/marcos.albe/anydbver/anydbver --namespace=gr ssh node4
screen -t DC2_N2 5 /home/marcos.albe/anydbver/anydbver --namespace=gr ssh node5
screen -t DC2_N3 6 /home/marcos.albe/anydbver/anydbver --namespace=gr ssh node6
```
For extra-coolness points it would be awesome to also have split window with `tail -F <log for the service deployed in the node>` in each tab.

**Comment by ihanick** [comment]
in initial implementation, tab names are just node names, as a next iteration it could be useful to have host names (if user sets it)
