### ISSUE TITLE
Add dedicated network interface for SSH

### ISSUE THREAD

**Issue by markusalbe** [ihanick/anydbver#26]
Hey Nickolay! Here's one more idea:

Add a second network interface to handle only the ssh traffic, so that we use iptables/qdisc to break the network connecting the services and clients , and still be able to access the nodes.

**Comment by ihanick** [comment]
Hi @markusalbe ,
With default docker provider there is an `anydbver exec node0` command similar to `anydbver ssh node0`, but it works even if the network is blocked. Please re-open if it's not enough
