### ISSUE TITLE
Error on deploy mariadb-cluster:10.3.26

### ISSUE THREAD

**Issue by vgrippa** [ihanick/anydbver#5]
Hi Nickolay,

I tried to deploy the Maria Cluster:

`./anydbver deploy mariadb-cluster:10.3.26`

But it is throwing this error:

`fatal: [vinicius.grippa.default]: FAILED! => {"changed": false, "msg": "Failure downloading https://archive.mariadb.org/mariadb-10.3.26/yum/centos7-amd64/rpms/galera-25.3.31-1.rhel7.el7.centos.x86_64.rpm, HTTP Error 404: Not Found"}`

Checking the repo and the only available for 25.3.31 is galera-25.3.31-1.el7.centos.x86_64.rpm.

**Comment by ihanick** [comment]
MariaDB finally removed rhel7 from galera package name. Added a condition to support both new and old naming
