### ISSUE TITLE
Vanilla mysql version in el7 is only recognized up to 8.0.21

### ISSUE THREAD

**Issue by ggreenworld** [ihanick/anydbver#6]
Hello,

Thanks for creating a great tool.

I tried to deploy with the latest version of Vanilla mysql, but I got the following error.
```
$ ./anydbver deploy mysql:8.0.25 xtrabackup
No such version mysql for el7: 'mysql:8.0.25'
$ ./anydbver deploy mysql:8.0.24 xtrabackup
No such version mysql for el7: 'mysql:8.0.24'
```

I see, this is how the script gets the version information from the Yum repository.

```
  curl -s \
    http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/ \
    http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/ \
    http://repo.mysql.com/yum/mysql-8.0-community/el/7/x86_64/ \
    | sed -rne 's/^.*HREF="mysql-community-server-([0-9].*)\.el.\.x86_64\.rpm".*$/\1/p' \
    | sort -t. -k 1,1n -k 2,2n -k 3,3n \
    > .version-info/mysql.el7.txt
```

When I access the URL of the repository, the page does indeed show only up to 8.0.21.
http://repo.mysql.com/yum/mysql-8.0-community/el/7/x86_64/

In the reference manual, it was an HTTPS URL.
https://dev.mysql.com/doc/mysql-yum-repo-quick-guide/en/#repo-enable-and-disable-sub-repositories

If I access the site via HTTPS, I see the version 8.0.22 or later.
http**s**://repo.mysql.com/yum/mysql-8.0-community/el/7/x86_64/

> [FILE] mysql-community-client-8.0.22-..> 25-Sep-2020 08:58  48.2M  
> [FILE] mysql-community-client-8.0.22-..> 25-Sep-2020 08:58  47.5M  
> [FILE] mysql-community-client-8.0.23-..> 16-Dec-2020 09:14  48.4M  
> [FILE] mysql-community-client-8.0.23-..> 16-Dec-2020 09:14  47.8M  
> [FILE] mysql-community-client-8.0.24-..> 23-Mar-2021 11:53  46.0M  
> [FILE] mysql-community-client-8.0.24-..> 23-Mar-2021 11:53  45.5M  
> [FILE] mysql-community-client-8.0.25-..> 26-Apr-2021 07:36  46.1M  
> [FILE] mysql-community-client-8.0.25-..> 26-Apr-2021 07:36  45.6M 

I actually changed it to HTTPS and the deployment went well.
```
$ ./anydbver update
$ tail .version-info/mysql.el7.txt
8.0.16-2
8.0.17-1
8.0.18-1
8.0.19-1
8.0.20-1
8.0.21-1
8.0.22-1
8.0.23-1
8.0.24-1
8.0.25-1
```
```
$ ./anydbver deploy mysql:8.0.25
(...)
$ ./anydbver ssh default 'mysqld --version'
/usr/sbin/mysqld  Ver 8.0.25 for Linux on x86_64 (MySQL Community Server - GPL)
```

**Comment by ihanick** [comment]
@ggreenworld Thank you for the report and fix! sorry for the long delay
